"""
统一异常处理机制
"""
from enum import Enum
from typing import Optional


class ErrorCode(Enum):
    """错误码枚举"""
    # 通用错误
    SUCCESS = "SUCCESS"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    NOT_FOUND = "NOT_FOUND"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"

    # 用户相关
    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
    USER_PASSWORD_INCORRECT = "USER_PASSWORD_INCORRECT"
    USER_ACCOUNT_LOCKED = "USER_ACCOUNT_LOCKED"
    USER_ACCOUNT_EXPIRED = "USER_ACCOUNT_EXPIRED"
    USERNAME_EXISTS = "USERNAME_EXISTS"
    OLD_PASSWORD_INCORRECT = "OLD_PASSWORD_INCORRECT"
    PASSWORDS_DO_NOT_MATCH = "PASSWORDS_DO_NOT_MATCH"
    SAME_AS_OLD_PASSWORD = "SAME_AS_OLD_PASSWORD"
    USER_ROLE_NOT_FOUND = "USER_ROLE_NOT_FOUND"

    # 角色相关
    ROLE_ALREADY_EXISTS = "ROLE_ALREADY_EXISTS"
    ROLE_NOT_FOUND = "ROLE_NOT_FOUND"
    ROLE_CODE_EXISTS = "ROLE_CODE_EXISTS"
    ROLE_NAME_EXISTS = "ROLE_NAME_EXISTS"
    SYSTEM_ROLE_CANNOT_DELETE = "SYSTEM_ROLE_CANNOT_DELETE"

    # 权限相关
    PERMISSION_DENIED = "PERMISSION_DENIED"

    # 内容相关
    CONTENT_NOT_FOUND = "CONTENT_NOT_FOUND"
    CONTENT_TYPE_INVALID = "CONTENT_TYPE_INVALID"
    CONTENT_NAME_EXISTS = "CONTENT_NAME_EXISTS"
    CONTENT_TYPE_NOT_FOUND = "CONTENT_TYPE_NOT_FOUND"
    CONTENT_TYPE_NAME_EXISTS = "CONTENT_TYPE_NAME_EXISTS"
    CONTENT_NO_LICENSE_BOUND = "CONTENT_NO_LICENSE_BOUND"
    CONTENT_ID_NOT_FOUND = "CONTENT_ID_NOT_FOUND"
    CONTENT_METADATA_NOT_FOUND = "CONTENT_METADATA_NOT_FOUND"
    CONTENT_METADATA_EXISTS = "CONTENT_METADATA_EXISTS"
    CONTENT_HAS_CHILDREN = "CONTENT_HAS_CHILDREN"
    CONTENT_PUBLISHED_CANNOT_DISCARD = "CONTENT_PUBLISHED_CANNOT_DISCARD"

    # 剧集/系列相关
    EPISODE_REQUIRES_SERIES = "EPISODE_REQUIRES_SERIES"
    EPISODE_PARENT_MUST_BE_SERIES = "EPISODE_PARENT_MUST_BE_SERIES"
    EPISODE_SEQUENCE_EXISTS = "EPISODE_SEQUENCE_EXISTS"
    SERIES_ORDINAL_EXISTS = "SERIES_ORDINAL_EXISTS"
    SCHEDULE_REQUIRES_CHANNEL = "SCHEDULE_REQUIRES_CHANNEL"
    SCHEDULE_PARENT_MUST_BE_CHANNEL = "SCHEDULE_PARENT_MUST_BE_CHANNEL"

    # 频道/节目单相关
    CHANNEL_NOT_FOUND_OR_WRONG_TYPE = "CHANNEL_NOT_FOUND_OR_WRONG_TYPE"
    START_TIME_BEFORE_END_TIME = "START_TIME_BEFORE_END_TIME"
    SCHEDULE_NOT_FOUND = "SCHEDULE_NOT_FOUND"
    CHANNEL_NOT_FOUND = "CHANNEL_NOT_FOUND"
    PHYSICAL_CHANNEL_NOT_FOUND = "PHYSICAL_CHANNEL_NOT_FOUND"
    CHANNEL_LINK_NOT_FOUND = "CHANNEL_LINK_NOT_FOUND"
    CUTV_NOT_ENABLED = "CUTV_NOT_ENABLED"
    INVALID_SERIES_TYPE = "INVALID_SERIES_TYPE"
    SCHEDULED_TIME_REQUIRED = "SCHEDULED_TIME_REQUIRED"
    CHANNEL_METADATA_NOT_FOUND = "CHANNEL_METADATA_NOT_FOUND"
    CHANNEL_METADATA_EXISTS = "CHANNEL_METADATA_EXISTS"
    SCHEDULE_METADATA_NOT_FOUND = "SCHEDULE_METADATA_NOT_FOUND"
    SCHEDULE_METADATA_EXISTS = "SCHEDULE_METADATA_EXISTS"
    SERIES_METADATA_NOT_FOUND = "SERIES_METADATA_NOT_FOUND"
    SERIES_METADATA_EXISTS = "SERIES_METADATA_EXISTS"

    # 供应商相关
    PROVIDER_NOT_FOUND = "PROVIDER_NOT_FOUND"
    PROVIDER_NAME_EXISTS = "PROVIDER_NAME_EXISTS"
    PROVIDER_HAS_CONTRACTS = "PROVIDER_HAS_CONTRACTS"
    PROVIDER_CODE_EXISTS = "PROVIDER_CODE_EXISTS"
    PROVIDER_NAME_WHITESPACE = "PROVIDER_NAME_WHITESPACE"
    PROVIDER_CODE_EMPTY = "PROVIDER_CODE_EMPTY"
    SUPPLIER_LIMIT_EXCEEDED = "SUPPLIER_LIMIT_EXCEEDED"

    # 合同相关
    CONTRACT_NOT_FOUND = "CONTRACT_NOT_FOUND"
    CONTRACT_NAME_EXISTS = "CONTRACT_NAME_EXISTS"
    CONTRACT_NAME_WHITESPACE = "CONTRACT_NAME_WHITESPACE"
    CONTRACT_HAS_LICENSES = "CONTRACT_HAS_LICENSES"
    ATTACHMENT_NOT_FOUND = "ATTACHMENT_NOT_FOUND"

    # 许可证相关
    LICENSE_NOT_FOUND = "LICENSE_NOT_FOUND"
    LICENSE_NAME_EXISTS = "LICENSE_NAME_EXISTS"
    LICENSE_HAS_CONTENTS = "LICENSE_HAS_CONTENTS"
    LICENSE_EXPIRED = "LICENSE_EXPIRED"

    # 服务包相关
    PACKAGE_NOT_FOUND = "PACKAGE_NOT_FOUND"
    PACKAGE_NAME_EXISTS = "PACKAGE_NAME_EXISTS"

    # 多中心相关
    NOT_MASTER_PLATFORM = "NOT_MASTER_PLATFORM"
    READONLY_MODE = "READONLY_MODE"  # 非主中心只读模式

    # 栏目相关
    CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND"
    CATEGORY_HAS_CHILDREN = "CATEGORY_HAS_CHILDREN"
    CATEGORY_HAS_CONTENTS = "CATEGORY_HAS_CONTENTS"
    CATEGORY_NAME_EXISTS = "CATEGORY_NAME_EXISTS"
    CATEGORY_NAME_EXISTS_UNDER_PARENT = "CATEGORY_NAME_EXISTS_UNDER_PARENT"
    CATEGORY_CONTENT_LIMIT_EXCEEDED = "CATEGORY_CONTENT_LIMIT_EXCEEDED"

    # 标签相关
    TAG_NOT_FOUND = "TAG_NOT_FOUND"
    TAG_NAME_EXISTS = "TAG_NAME_EXISTS"
    CUSTOM_TAG_NOT_FOUND = "CUSTOM_TAG_NOT_FOUND"
    CUSTOM_TAG_NAME_EXISTS = "CUSTOM_TAG_NAME_EXISTS"

    # 海报规格相关
    POSTER_SIZE_NOT_FOUND = "POSTER_SIZE_NOT_FOUND"
    POSTER_SIZE_NAME_EXISTS = "POSTER_SIZE_NAME_EXISTS"

    # 题材相关
    GENRE_NOT_FOUND = "GENRE_NOT_FOUND"
    GENRE_NAME_EXISTS = "GENRE_NAME_EXISTS"

    # 数据源相关
    METADATA_SOURCE_NOT_FOUND = "METADATA_SOURCE_NOT_FOUND"

    # 爬取任务相关
    CRAWL_TASK_NOT_FOUND = "CRAWL_TASK_NOT_FOUND"
    CRAWL_NO_SOURCE_AVAILABLE = "CRAWL_NO_SOURCE_AVAILABLE"
    CRAWL_TASK_RETRY_INVALID_STATUS = "CRAWL_TASK_RETRY_INVALID_STATUS"
    SOURCE_HAS_INPROGRESS_TASK = "SOURCE_HAS_INPROGRESS_TASK"
    SOURCE_API_KEY_REQUIRED = "SOURCE_API_KEY_REQUIRED"

    # 文件相关
    FILE_NOT_FOUND = "FILE_NOT_FOUND"
    FILE_READ_ERROR = "FILE_READ_ERROR"
    XML_FILE_ONLY = "XML_FILE_ONLY"
    INVALID_FILE_FORMAT = "INVALID_FILE_FORMAT"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    IMAGE_WIDTH_NOT_MEET = "IMAGE_WIDTH_NOT_MEET"
    IMAGE_HEIGHT_NOT_MEET = "IMAGE_HEIGHT_NOT_MEET"
    PICTURE_NOT_FOUND = "PICTURE_NOT_FOUND"

    # 工作流配置相关
    WORKFLOW_CONFIG_NOT_FOUND = "WORKFLOW_CONFIG_NOT_FOUND"
    WORKFLOW_CONFIG_DRAFT_EXISTS = "WORKFLOW_CONFIG_DRAFT_EXISTS"
    WORKFLOW_CONFIG_PUBLISHED_CANNOT_EDIT = "WORKFLOW_CONFIG_PUBLISHED_CANNOT_EDIT"
    WORKFLOW_CONFIG_EMPTY = "WORKFLOW_CONFIG_EMPTY"
    WORKFLOW_CONFIG_JSON_INVALID = "WORKFLOW_CONFIG_JSON_INVALID"
    WORKFLOW_CONFIG_ONLY_UNPUBLISH_PUBLISHED = "WORKFLOW_CONFIG_ONLY_UNPUBLISH_PUBLISHED"

    # 审核相关
    REVIEW_RECORD_NOT_FOUND = "REVIEW_RECORD_NOT_FOUND"
    REVIEW_ALREADY_COMPLETED = "REVIEW_ALREADY_COMPLETED"
    REVIEW_TASK_NOT_FOUND = "REVIEW_TASK_NOT_FOUND"
    REVIEW_NO_PERMISSION = "REVIEW_NO_PERMISSION"
    REVIEW_ALREADY_IN_PROGRESS = "REVIEW_ALREADY_IN_PROGRESS"

    # 字典相关
    DICT_NODE_NOT_FOUND = "DICT_NODE_NOT_FOUND"
    DICT_CODE_EXISTS = "DICT_CODE_EXISTS"
    DICT_NAME_EXISTS = "DICT_NAME_EXISTS"
    DICT_HAS_CHILDREN = "DICT_HAS_CHILDREN"
    SYSTEM_DICT_CANNOT_DELETE = "SYSTEM_DICT_CANNOT_DELETE"
    DICT_SENSITIVE_WORD_TYPE_NOT_FOUND = "DICT_SENSITIVE_WORD_TYPE_NOT_FOUND"

    # 菜单相关
    MENU_NOT_FOUND = "MENU_NOT_FOUND"
    PARENT_MENU_NOT_FOUND = "PARENT_MENU_NOT_FOUND"
    MENU_CIRCULAR_REF = "MENU_CIRCULAR_REF"

    # 定时任务相关
    SCHEDULED_TASK_NOT_FOUND = "SCHEDULED_TASK_NOT_FOUND"
    SCHEDULED_TASK_IDS_NOT_FOUND = "SCHEDULED_TASK_IDS_NOT_FOUND"
    SCHEDULED_TASK_RUNNING_BLOCKED = "SCHEDULED_TASK_RUNNING_BLOCKED"
    SCHEDULED_TASK_DISABLED_BLOCKED = "SCHEDULED_TASK_DISABLED_BLOCKED"

    # 元数据质量相关
    METADATA_QUALITY_CHECK_NOT_FOUND = "METADATA_QUALITY_CHECK_NOT_FOUND"

    # 元数据校验规则相关
    VALIDATION_RULE_NOT_FOUND = "VALIDATION_RULE_NOT_FOUND"
    VALIDATION_RULE_ALREADY_EXISTS = "VALIDATION_RULE_ALREADY_EXISTS"
    SYSTEM_RULE_CANNOT_DELETE = "SYSTEM_RULE_CANNOT_DELETE"
    INVALID_ENTITY_TYPE = "INVALID_ENTITY_TYPE"
    INVALID_RULE_TYPE = "INVALID_RULE_TYPE"
    INVALID_SEVERITY_LEVEL = "INVALID_SEVERITY_LEVEL"
    EXCEL_IMPORT_FAILED = "EXCEL_IMPORT_FAILED"

    # 配置相关
    CONFIG_NOT_FOUND = "CONFIG_NOT_FOUND"
    CONFIG_CODE_EXISTS = "CONFIG_CODE_EXISTS"
    SYSTEM_CONFIG_CANNOT_DELETE = "SYSTEM_CONFIG_CANNOT_DELETE"

    # 自定义字段相关
    CUSTOM_FIELD_NOT_FOUND = "CUSTOM_FIELD_NOT_FOUND"
    CUSTOM_FIELD_NAME_EXISTS = "CUSTOM_FIELD_NAME_EXISTS"
    CUSTOM_FIELD_OPTION_CODE_DUPLICATE = "CUSTOM_FIELD_OPTION_CODE_DUPLICATE"

    # 人物相关
    CAST_NOT_FOUND = "CAST_NOT_FOUND"
    CAST_NAME_EXISTS = "CAST_NAME_EXISTS"
    CAST_ROLE_MAP_NOT_FOUND = "CAST_ROLE_MAP_NOT_FOUND"

    # 媒资相关
    MOVIE_NOT_FOUND = "MOVIE_NOT_FOUND"

    # 任务相关
    TASK_NOT_FOUND = "TASK_NOT_FOUND"
    TASK_COMPLETED_CANNOT_MODIFY = "TASK_COMPLETED_CANNOT_MODIFY"

    # 发布相关
    PUBLISH_TASK_NOT_FOUND = "PUBLISH_TASK_NOT_FOUND"
    PUBLISH_PLAN_ALREADY_EXISTS = "PUBLISH_PLAN_ALREADY_EXISTS"
    PUBLISH_TASK_IN_PROGRESS = "PUBLISH_TASK_IN_PROGRESS"
    PUBLISH_TASK_CANNOT_MODIFY = "PUBLISH_TASK_CANNOT_MODIFY"
    PUBLISH_TASK_CANNOT_CANCEL = "PUBLISH_TASK_CANNOT_CANCEL"
    CONTENT_ALREADY_PUBLISHED = "CONTENT_ALREADY_PUBLISHED"

    # 登录相关
    CAPTCHA_INVALID = "CAPTCHA_INVALID"
    ACCOUNT_LOCKED_REMAINING = "ACCOUNT_LOCKED_REMAINING"
    ACCOUNT_LOCKED_PERMANENT = "ACCOUNT_LOCKED_PERMANENT"
    LOGIN_FAILED_WITH_REMAINING = "LOGIN_FAILED_WITH_REMAINING"
    LOGIN_FAILED = "LOGIN_FAILED"
    ACCOUNT_DISABLED = "ACCOUNT_DISABLED"
    INVALID_TOKEN = "INVALID_TOKEN"

    # 敏感词相关
    SENSITIVE_WORD_NOT_FOUND = "SENSITIVE_WORD_NOT_FOUND"
    SENSITIVE_WORD_EXISTS = "SENSITIVE_WORD_EXISTS"
    SENSITIVE_WORD_DETECTED = "SENSITIVE_WORD_DETECTED"

    # 使用限制相关
    USAGE_LIMIT_NOT_DEVELOPED = "USAGE_LIMIT_NOT_DEVELOPED"
    USAGE_LIMIT_TYPE_NOT_FOUND = "USAGE_LIMIT_TYPE_NOT_FOUND"

    # 审批级别相关
    REVIEW_LEVEL_APPROVED_WAITING_NEXT = "REVIEW_LEVEL_APPROVED_WAITING_NEXT"

    # 上传任务相关
    UPLOAD_TASK_NOT_FOUND = "UPLOAD_TASK_NOT_FOUND"
    CHUNK_NOT_FOUND = "CHUNK_NOT_FOUND"
    UPLOAD_FAILED = "UPLOAD_FAILED"
    CHUNK_SIZE_MISMATCH = "CHUNK_SIZE_MISMATCH"
    CHUNK_MD5_MISMATCH = "CHUNK_MD5_MISMATCH"
    CHUNKS_INCOMPLETE = "CHUNKS_INCOMPLETE"
    CHUNK_FILE_NOT_FOUND = "CHUNK_FILE_NOT_FOUND"
    FILE_SIZE_MISMATCH = "FILE_SIZE_MISMATCH"
    FILE_MD5_MISMATCH = "FILE_MD5_MISMATCH"
    MERGE_FAILED = "MERGE_FAILED"
    UPLOAD_CANCELLED = "UPLOAD_CANCELLED"


class BusinessException(Exception):
    """业务异常基类"""
    def __init__(
        self,
        error_code: ErrorCode,
        message: Optional[str] = None,
        status_code: int = 400
    ):
        self.error_code = error_code
        self.message = message or error_code.value
        self.status_code = status_code
        super().__init__(self.message)


class ValidationException(BusinessException):
    """验证异常"""
    def __init__(self, message: str = "Validation Error"):
        super().__init__(ErrorCode.VALIDATION_ERROR, message, 422)


class NotFoundException(BusinessException):
    """未找到异常"""
    def __init__(
        self,
        error_code: ErrorCode = ErrorCode.NOT_FOUND,
        message: Optional[str] = None,
    ):
        super().__init__(error_code, message or error_code.value, 404)


class UnauthorizedException(BusinessException):
    """未授权异常"""
    def __init__(
        self,
        error_code: ErrorCode = ErrorCode.UNAUTHORIZED,
        message: Optional[str] = None,
    ):
        super().__init__(error_code, message or error_code.value, 401)


class ForbiddenException(BusinessException):
    """禁止访问异常"""
    def __init__(
        self,
        error_code: ErrorCode = ErrorCode.FORBIDDEN,
        message: Optional[str] = None,
    ):
        super().__init__(error_code, message or error_code.value, 403)
